### ISSUE TITLE
Require at least Python 3.7/Ansible 2.5

### ISSUE THREAD

**Issue by likeuntomurphy** [fostermadeco/rokanan#9]
2.7 no longer installable via homebrew.

Catalina comes with 3.7.3 if you don’t want to use homebrew — and 3.7 requires ansible 2.5 (2.4 is incompatible because of new reserved words in python 3.7).

**Comment by likeuntomurphy** [comment]
See https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html

**Comment by smaida** [comment]
Repo archived. Won't fix.
